<template>
  <div class="card flex flex-col gap-3">
    <!-- Header -->
    <div class="flex items-center gap-2 flex-wrap">
      <span class="text-xs font-mono text-gray-600 w-6 shrink-0">{{ scene.index }}</span>
      <span :class="statusBadge(scene.image_status)">img</span>
      <span :class="statusBadge(scene.audio_status)">aud</span>
      <span :class="statusBadge(scene.video_status)">vid</span>
      <span :class="statusBadge(scene.clip_status)">clip</span>
      <span class="ml-auto text-xs text-gray-600">{{ scene.duration }}s</span>
    </div>

    <!-- Media preview -->
    <div class="relative bg-black/30 rounded-lg overflow-hidden">
      <!-- compiled clip: full width with controls -->
      <video v-if="scene.compiled_clip_path" :src="scene.compiled_clip_path"
        class="w-full aspect-video object-cover" controls />
      <!-- both image and video: show side by side -->
      <div v-else-if="scene.image_path && scene.video_path" class="flex gap-1">
        <img :src="scene.image_path" class="w-1/2 aspect-video object-cover" />
        <img v-if="scene.video_path.endsWith('.webp')" :src="scene.video_path" class="w-1/2 aspect-video object-cover" />
        <video v-else :src="scene.video_path" class="w-1/2 aspect-video object-cover" autoplay loop muted />
      </div>
      <!-- video only -->
      <img v-else-if="scene.video_path?.endsWith('.webp')" :src="scene.video_path"
        class="w-full aspect-video object-cover" />
      <video v-else-if="scene.video_path" :src="scene.video_path"
        class="w-full aspect-video object-cover" autoplay loop muted />
      <!-- image only -->
      <img v-else-if="scene.image_path" :src="scene.image_path" class="w-full aspect-video object-cover" />
      <div v-else class="aspect-video flex items-center justify-center text-gray-700 text-xs">No media</div>
      <div v-if="isGenerating" class="absolute inset-0 bg-black/50 flex items-center justify-center">
        <div class="w-6 h-6 border-2 border-accent border-t-transparent rounded-full animate-spin" />
      </div>
    </div>

    <!-- Audio player -->
    <div v-if="scene.audio_path" class="flex items-center gap-2">
      <audio :src="scene.audio_path" controls class="w-full h-8" style="filter: invert(0.8) hue-rotate(200deg);" />
    </div>

    <!-- Description -->
    <div v-if="!editingDesc" class="text-xs text-gray-400 leading-relaxed cursor-text line-clamp-2"
      @click="startEditDesc">
      {{ scene.description || 'No description' }}
    </div>
    <textarea v-else v-model="editDesc" class="input text-xs resize-none h-16 font-mono"
      @blur="saveDesc" @keydown.escape="editingDesc = false" />

    <!-- Narration accordion -->
    <details class="group">
      <summary class="text-xs text-gray-600 cursor-pointer hover:text-gray-400 select-none flex items-center gap-1">
        <span class="group-open:rotate-90 transition-transform inline-block">▶</span>
        Narration
      </summary>
      <div class="mt-1 space-y-1">
        <textarea v-model="narrationText" class="input text-xs resize-none h-20 font-mono"
          placeholder="Narration will be generated by AI…"
          @blur="saveNarration" />
        <div class="flex gap-2 items-center">
          <select v-model="ttsVoice" class="input text-xs py-1 flex-1">
            <option value="en-US-AriaNeural">Aria (US, F)</option>
            <option value="en-US-AvaNeural">Ava (US, F)</option>
            <option value="en-US-AndrewNeural">Andrew (US, M)</option>
            <option value="en-US-BrianNeural">Brian (US, M)</option>
            <option value="en-US-EmmaNeural">Emma (US, F)</option>
            <option value="en-GB-SoniaNeural">Sonia (UK, F)</option>
            <option value="en-GB-RyanNeural">Ryan (UK, M)</option>
          </select>
          <button class="btn-ghost text-xs shrink-0" @click="genAudio">🎙 TTS</button>
        </div>
      </div>
    </details>

    <!-- Prompts accordion -->
    <details class="group">
      <summary class="text-xs text-gray-600 cursor-pointer hover:text-gray-400 select-none flex items-center gap-1">
        <span class="group-open:rotate-90 transition-transform inline-block">▶</span>
        Prompts
      </summary>
      <div class="mt-1 space-y-2">
        <div>
          <p class="text-xs text-gray-700 mb-0.5">Visual</p>
          <textarea v-model="scene.visual_prompt" class="input text-xs resize-none h-16 font-mono"
            @blur="savePatch({ visual_prompt: scene.visual_prompt })" />
          <button class="text-xs text-accent hover:underline" @click="genVisualPrompt">↻ Regen</button>
        </div>
        <div>
          <p class="text-xs text-gray-700 mb-0.5">Video</p>
          <textarea v-model="scene.video_prompt" class="input text-xs resize-none h-16 font-mono"
            @blur="savePatch({ video_prompt: scene.video_prompt })" />
          <button class="text-xs text-accent hover:underline" @click="genVideoPrompt">↻ Regen</button>
        </div>
      </div>
    </details>

    <!-- Model controls -->
    <div class="flex gap-2">
      <select v-model="imageModel" class="input text-xs py-1 w-36" title="Image model">
        <option value="flux-schnell">Flux Schnell</option>
        <option value="ernie-image">ERNIE Image</option>
        <option value="ernie-image-turbo">ERNIE Turbo</option>
      </select>
    </div>
    <div class="flex gap-2">
      <select v-model="videoModel" class="input text-xs py-1 flex-1"
        @change="savePatch({ video_model: videoModel })">
        <option value="wan2.2-t2v">Wan2.2 T2V</option>
        <option value="wan2.2-i2v">Wan2.2 I2V</option>
        <option value="hunyuan-t2v">Hunyuan T2V</option>
        <option value="hunyuan-i2v">Hunyuan I2V</option>
        <option value="ltxv-t2v">LTXV T2V</option>
        <option value="ltxv-i2v">LTXV I2V</option>
      </select>
      <select v-model="resolution" class="input text-xs py-1 w-20"
        @change="savePatch({ resolution })">
        <option value="480p">480p</option>
        <option value="720p">720p</option>
      </select>
    </div>

    <!-- Action buttons -->
    <div class="grid grid-cols-4 gap-1.5">
      <button class="btn-ghost text-xs py-1" :disabled="scene.image_status === 'generating'" @click="genImage" title="Generate image">🖼</button>
      <button class="btn-ghost text-xs py-1" :disabled="scene.audio_status === 'generating'" @click="genAudioFull" title="Generate narration + audio">🎙</button>
      <button class="btn-primary text-xs py-1" :disabled="scene.video_status === 'generating'" @click="genVideo" title="Generate video">🎬</button>
      <button class="btn-ghost text-xs py-1" :disabled="scene.clip_status === 'generating'" @click="compileClip" title="Compile clip (video+audio)">⚙</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { io } from 'socket.io-client'

const props = defineProps<{ scene: any; projectRatio: string }>()
const emit = defineEmits<{ updated: [] }>()

const editingDesc = ref(false)
const editDesc = ref(props.scene.description)
const narrationText = ref(props.scene.narration ?? '')
const imageModel = ref('flux-schnell')
const videoModel = ref(props.scene.video_model ?? 'wan2.2-t2v')
const resolution = ref(props.scene.resolution ?? '480p')
const ttsVoice = ref(props.scene.tts_voice ?? 'en-US-AriaNeural')

const isGenerating = computed(() =>
  ['generating'].includes(props.scene.image_status) ||
  ['generating'].includes(props.scene.video_status) ||
  ['generating'].includes(props.scene.audio_status) ||
  ['generating'].includes(props.scene.clip_status),
)

const socket = io({ path: '/socket.io' })
socket.on('prompt:done', ({ sceneId, prompt }: any) => {
  if (sceneId === props.scene.id) { props.scene.visual_prompt = prompt; emit('updated') }
})
socket.on('vprompt:done', ({ sceneId, prompt }: any) => {
  if (sceneId === props.scene.id) { props.scene.video_prompt = prompt; emit('updated') }
})

function statusBadge(s: string) {
  if (s === 'generating') return 'badge-generating'
  if (s === 'done') return 'badge-done'
  if (s === 'error') return 'badge-error'
  return 'badge-idle'
}

function startEditDesc() { editDesc.value = props.scene.description; editingDesc.value = true }

async function savePatch(data: any) {
  await fetch(`/api/scenes/${props.scene.id}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  })
  emit('updated')
}

async function saveDesc() {
  editingDesc.value = false
  props.scene.description = editDesc.value
  await savePatch({ description: editDesc.value })
}

async function saveNarration() {
  await fetch(`/api/audio/scene/${props.scene.id}/narration`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ narration: narrationText.value }),
  })
}

async function genImage() {
  await fetch(`/api/scenes/${props.scene.id}/image`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ image_model: imageModel.value }),
  })
  props.scene.image_status = 'generating'
}

async function genVideo() {
  await fetch(`/api/scenes/${props.scene.id}/video`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: videoModel.value, resolution: resolution.value }),
  })
  props.scene.video_status = 'generating'
}

// generate audio from existing narration text only (TTS only)
async function genAudio() {
  await saveNarration()
  if (!narrationText.value) return genAudioFull()
  await fetch(`/api/audio/scene/${props.scene.id}/tts`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ voice: ttsVoice.value }),
  })
  props.scene.audio_status = 'generating'
}

// generate narration with Ollama then TTS
async function genAudioFull() {
  await fetch(`/api/audio/scene/${props.scene.id}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ voice: ttsVoice.value }),
  })
  props.scene.audio_status = 'generating'
}

async function compileClip() {
  await fetch(`/api/compile/clip/${props.scene.id}`, { method: 'POST' })
  props.scene.clip_status = 'generating'
}

function genVisualPrompt() {
  socket.emit('scene:visual-prompt', {
    sceneId: props.scene.id,
    description: props.scene.description,
    style: 'cinematic',
  })
}

function genVideoPrompt() {
  socket.emit('scene:video-prompt', {
    sceneId: props.scene.id,
    description: props.scene.description,
    visualPrompt: props.scene.visual_prompt,
  })
}
</script>
